### ISSUE TITLE
PyLint check

### ISSUE THREAD

**Issue by jspiel** [nyu-devops-recommendations/recommendations#17]
**As a** consumer of the recommendations API
**I need** to see be able to update a resource (recommendation)
**So that** I can modify its contents as appropriate

**Assumptions:**
* responses will be json
* update the appropriate resource when when user performs PUT (really?) to /recommendations/123

**Acceptance Criteria:**
```
Given
When
Then
```

**Comment by lanloons** [comment]
Tested 3/25 @9:38ish and here are the results:

************* Module tests.__init__
C:  2, 0: Final newline missing (missing-final-newline)
************* Module tests
C:  1, 0: Missing module docstring (missing-docstring)
************* Module tests.test_recommendations
E: 26, 0: Unable to import 'app' (import-error)
C: 33, 0: Missing class docstring (missing-docstring)
C: 54, 4: Missing method docstring (missing-docstring)
C: 63, 4: Missing method docstring (missing-docstring)
C:113, 4: Method name "test_deserialize_a_recommendation" doesn't conform to snake_case naming style (invalid-name)
************* Module tests.test_server
C: 72, 0: Line too long (111/100) (line-too-long)
C:150, 0: Exactly one space required before assignment
        test_association= recommendations[0].association
                        ^ (bad-whitespace)
C:151, 0: Line too long (142/100) (line-too-long)
E: 27, 0: Unable to import 'flask_api' (import-error)
E: 30, 0: Unable to import 'tests.recommendation_factory' (import-error)
E: 31, 0: Unable to import 'app.service' (import-error)
C:103, 4: Method name "test_get_recommendation_not_found" doesn't conform to snake_case naming style (invalid-name)
C:147, 4: Method name "test_query_recommendation_list_by_association" doesn't conform to snake_case naming style (invalid-name)
W: 29, 0: Unused Recommendation imported from app.models (unused-import)
W: 29, 0: Unused DataValidationError imported from app.models (unused-import)
C: 31, 0: first party import "import app.service as service" should be placed before "from .recommendation_factory import RecommendationFactory" (wrong-import-order)

-----------------------------------
Your code has been rated at 8.20/10
