### ISSUE TITLE
Create Sprint Burndown Chart

### ISSUE THREAD

**Issue by rossmemole** [nyu-devops-recommendations/recommendations#4]
** As a scrum master**
**I need a burndown chart**
**So that my team and I complete our deliverables on-time**

**Assumption:**
*Everyone will follow the burndown

**Comment by rossmemole** [comment]
Need Milestone Date Edit Access

**Comment by jspiel** [comment]
Had to set spring start dates. All set.

**Comment by rossmemole** [comment]
Need to add members to Repository in order to edit Issue stage in Zenhub
