### ISSUE TITLE
Add a Travis CI badge to README.md file

### ISSUE THREAD

**Issue by rossmemole** [nyu-devops-recommendations/recommendations#43]
**As a developer**
**I need to have a Travis CI badge in our README.md file**
**So that Travis CI recognizes when to run a test case after a push to the master branch or when someone issues a pull request**

**Assumptions:**
* The Travis CI badge is necessary for Travis CI to successfully crawl the README.md file

**Acceptance Criteria:**
```
Given the need to test new code before it is merged into the master branch
When issuing a pull request or a push to the master branch
Then the Travis CI badge within the README.md file will successfully deploy a test case before the code is merged
```

**Comment by jspiel** [comment]
URL for the image is:
https://travis-ci.org/nyu-devops-recommendations/recommendations.svg?branch=master

**Comment by lanloons** [comment]
Copy pasted the following into our ReadMe file:

[![Build Status](https://travis-ci.org/nyu-devops-recommendations/recommendations.svg?branch=master)](https://travis-ci.org/nyu-devops-recommendations/recommendations)

I now see a badge, but it's saying build is unknown. Is this accurate?

**Comment by jspiel** [comment]
Keeping this assigned to you @lanloons because I think this should be fine once we do a PR
