### ISSUE TITLE
Modify application to get database credentials

### ISSUE THREAD

**Issue by rossmemole** [nyu-devops-recommendations/recommendations#47]
**As a developer**
**I need to ensure that the application can retrieve database credentials**
**So that we can successfully run with persistence**

**Assumptions:**
* Need to use VCAP_SERVICES or DATABASE_URI depending on the database

**Acceptance Criteria:**
```
Given the need to have an application with persistence
When running a microservice in a cloud environment
Then the application will successfully retrieve the underlying database credentials 
```

**Comment by lanloons** [comment]
Duplicate and therefore closing.
