### ISSUE TITLE
Go to the URL of your service and make sure that it works

### ISSUE THREAD

**Issue by rossmemole** [nyu-devops-recommendations/recommendations#57]
**As a developer**
**I need to check the URL of the recommendations service**
**So that we can make sure it works for other users**

**Assumptions:**
* Assuming that the CF push to IBM Cloud worked

**Acceptance Criteria:**
```
Given the importance of test driven development 
When clicking through on the service URL
Then the application will run in the cloud
```

**Comment by rossmemole** [comment]
link to the url: nyu-recommendations-service-s19.mybluemix.net

**Comment by lanloons** [comment]
The URL is actually: nyu-recommendation-service-s19.mybluemix.net

Once that is corrected it works! :D
